### ISSUE TITLE
Support for non-Delimited file types in Redshift

### ISSUE THREAD

**Issue by fdosani** [capitalone/locopy#39]
https://docs.aws.amazon.com/redshift/latest/dg/copy-parameters-data-format.html

**Comment by jfyu** [comment]
Can I add a +1 to this issue 😂 currently running into this now. It seems to me that you just have to not include `DELIMITER` as an option? i.e. make [this line](https://github.com/capitalone/locopy/blob/develop/locopy/redshift.py#L379) optional only if `deliminter is not None` ? 

Also now I'm using locopy because Redshift really has crappy python connector....

**Comment by fdosani** [comment]
@jfyu happy to accept a PR too if you have some time 😄
